/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnMenuRouteImport } from './routes/en.menu'
import { Route as ApiMenuRouteImport } from './routes/api.menu'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as ApiMenuLoginRouteImport } from './routes/api.menu.login'
import { Route as ApiMenuImageRouteImport } from './routes/api.menu.image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnMenuRoute = EnMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => EnRoute,
} as any)
const ApiMenuRoute = ApiMenuRouteImport.update({
  id: '/api/menu',
  path: '/api/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuLoginRoute = ApiMenuLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ApiMenuRoute,
} as any)
const ApiMenuImageRoute = ApiMenuImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiMenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/menu': typeof AdminMenuRoute
  '/api/menu': typeof ApiMenuRouteWithChildren
  '/en/menu': typeof EnMenuRoute
  '/en/': typeof EnIndexRoute
  '/api/menu/image': typeof ApiMenuImageRoute
  '/api/menu/login': typeof ApiMenuLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/menu': typeof AdminMenuRoute
  '/api/menu': typeof ApiMenuRouteWithChildren
  '/en/menu': typeof EnMenuRoute
  '/en': typeof EnIndexRoute
  '/api/menu/image': typeof ApiMenuImageRoute
  '/api/menu/login': typeof ApiMenuLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRouteWithChildren
  '/menu': typeof MenuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/menu': typeof AdminMenuRoute
  '/api/menu': typeof ApiMenuRouteWithChildren
  '/en/menu': typeof EnMenuRoute
  '/en/': typeof EnIndexRoute
  '/api/menu/image': typeof ApiMenuImageRoute
  '/api/menu/login': typeof ApiMenuLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/menu'
    | '/sitemap.xml'
    | '/admin/menu'
    | '/api/menu'
    | '/en/menu'
    | '/en/'
    | '/api/menu/image'
    | '/api/menu/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu'
    | '/sitemap.xml'
    | '/admin/menu'
    | '/api/menu'
    | '/en/menu'
    | '/en'
    | '/api/menu/image'
    | '/api/menu/login'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/menu'
    | '/sitemap.xml'
    | '/admin/menu'
    | '/api/menu'
    | '/en/menu'
    | '/en/'
    | '/api/menu/image'
    | '/api/menu/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRouteWithChildren
  MenuRoute: typeof MenuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminMenuRoute: typeof AdminMenuRoute
  ApiMenuRoute: typeof ApiMenuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/menu': {
      id: '/en/menu'
      path: '/menu'
      fullPath: '/en/menu'
      preLoaderRoute: typeof EnMenuRouteImport
      parentRoute: typeof EnRoute
    }
    '/api/menu': {
      id: '/api/menu'
      path: '/api/menu'
      fullPath: '/api/menu'
      preLoaderRoute: typeof ApiMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu/login': {
      id: '/api/menu/login'
      path: '/login'
      fullPath: '/api/menu/login'
      preLoaderRoute: typeof ApiMenuLoginRouteImport
      parentRoute: typeof ApiMenuRoute
    }
    '/api/menu/image': {
      id: '/api/menu/image'
      path: '/image'
      fullPath: '/api/menu/image'
      preLoaderRoute: typeof ApiMenuImageRouteImport
      parentRoute: typeof ApiMenuRoute
    }
  }
}

interface EnRouteChildren {
  EnMenuRoute: typeof EnMenuRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnMenuRoute: EnMenuRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface ApiMenuRouteChildren {
  ApiMenuImageRoute: typeof ApiMenuImageRoute
  ApiMenuLoginRoute: typeof ApiMenuLoginRoute
}

const ApiMenuRouteChildren: ApiMenuRouteChildren = {
  ApiMenuImageRoute: ApiMenuImageRoute,
  ApiMenuLoginRoute: ApiMenuLoginRoute,
}

const ApiMenuRouteWithChildren =
  ApiMenuRoute._addFileChildren(ApiMenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRouteWithChildren,
  MenuRoute: MenuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminMenuRoute: AdminMenuRoute,
  ApiMenuRoute: ApiMenuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
